// 左侧菜单tree
const siderTreeList = [
    {
        id: '1',
        path: '/home',
        title: '首页',
        icon: 'md-home',
        applyName: 'base',
        auth: true,
        name: 'home',
        authMark: '1',
        isShow: true,
    },
    {
        id: '2',
        path: '/sub-vue2/export/list',
        title: '导出列表',
        applyName: 'sub-vue2',
        icon: 'md-download',
        auth: true,
        name: 'sub-vue2-export-list',
        authMark: '2',
        isShow: true,
    },
    {
        id: '3',
        path: '/warehouse',
        name: 'warehouse',
        title: '条码入库',
        icon: 'ios-archive',
        authMark: '3',
        isShow: true,
        children: [
            {
                id: '3-1',
                path: '/sub-vue2/warehouse/entry/list',
                title: '入库管理',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-warehouse-entry-list',
                parentName: 'warehouse',
                authMark: '3-1',
                isShow: true,
            },
            {
                id: '3-2',
                path: '/sub-vue2/warehouse/entry/edit',
                title: '入库管理订单详情',
                icon: '',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-warehouse-entry-edit',
                activeName: 'sub-vue2-warehouse-entry-list',
                parentName: 'warehouse',
                authMark: '3-1',
                isShow: true,
            },
        ],
    },
    {
        id: '4',
        path: '/scan',
        name: 'scan',
        title: '扫码管理',
        icon: 'md-camera',
        authMark: '4',
        isShow: true,
        children: [
            {
                id: '4-1',
                path: '/sub-vue2/scan/flow/list',
                title: '扫码流水',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-scan-flow-list',
                parentName: 'scan',
                authMark: '4-1',
                isShow: true,
            },
            {
                id: '4-2',
                path: '/sub-vue2/scan/flow/detail',
                title: '扫码详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-scan-flow-detail',
                activeName: 'sub-vue2-scan-flow-list',
                parentName: 'scan',
                authMark: '4-1',
                isShow: true,
            },
            {
                id: '4-3',
                path: '/sub-vue2/scan/distributor/list',
                title: '经销商扫码异常',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-scan-distributor-list',
                parentName: 'scan',
                authMark: '4-2',
                isShow: true,
            },
            {
                id: '4-4',
                path: '/sub-vue2/scan/query/list',
                title: '条码/胎号查询',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-scan-query-list',
                parentName: 'scan',
                authMark: '4-3',
                isShow: true,
            },
        ],
    },
    {
        id: '5',
        path: '/customer',
        name: 'customer',
        title: '客户管理',
        icon: 'md-people',
        authMark: '5',
        isShow: true,
        children: [
            {
                id: '5-1',
                path: '/sub-vue2/customer/manage/list',
                title: '客户管理',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-customer-manage-list',
                parentName: 'customer',
                authMark: '5-1',
                isShow: true,
            },
            {
                id: '5-2',
                path: '/sub-vue2/customer/manage/storeDetail',
                title: '门店详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-customer-manage-storeDetail',
                activeName: 'sub-vue2-customer-manage-list',
                parentName: 'customer',
                authMark: '5-1',
                isShow: true,
            },
            {
                id: '5-3',
                path: '/sub-vue2/customer/manage/orderDetail',
                title: '门店详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-customer-manage-orderDetail',
                activeName: 'sub-vue2-customer-manage-list',
                parentName: 'customer',
                authMark: '5-1',
                isShow: true,
            },
            {
                id: '5-4',
                path: '/sub-vue2/customer/storeSign/list',
                title: '门店签署管理',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-customer-storeSign-list',
                parentName: 'customer',
                authMark: '5-2',
                isShow: true,
            },
            {
                id: '5-5',
                path: '/sub-vue2/customer/storeSign/check',
                title: '门店签署详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-customer-storeSign-check',
                activeName: 'sub-vue2-customer-storeSign-list',
                parentName: 'customer',
                authMark: '5-2',
                isShow: true,
            },
        ],
    },
    {
        id: '6',
        path: '/credit',
        name: 'credit',
        title: '授信管理',
        icon: 'logo-euro',
        authMark: '6',
        isShow: true,
        children: [
            {
                id: '6-1',
                path: '/sub-vue2/credit/creditAccount/list',
                title: '授信账户',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-credit-creditAccount-list',
                parentName: 'credit',
                authMark: '6-1',
                isShow: true,
            },
            {
                id: '6-2',
                path: '/sub-vue2/credit/creditDetail/use',
                title: '授信使用',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-credit-creditDetail-use',
                parentName: 'credit',
                authMark: '6-2',
                isShow: true,
            },
            {
                id: '6-3',
                path: '/sub-vue2/credit/creditDetail/collection',
                title: '授信收款',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-credit-creditDetail-collection',
                parentName: 'credit',
                authMark: '6-3',
                isShow: true,
            },
            {
                id: '6-4',
                path: '/sub-vue2/credit/creditDetail/amount',
                title: '授信额度',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-credit-creditDetail-amount',
                parentName: 'credit',
                authMark: '6-4',
                isShow: true,
            },
            {
                id: '6-5',
                path: '/sub-vue2/credit/creditSetting/list',
                title: '授信设置',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-credit-creditSetting-list',
                parentName: 'credit',
                authMark: '6-5',
                isShow: true,
            },
        ],
    },
    {
        id: '7',
        path: '/decoration',
        name: 'decoration',
        title: '门店装修管理',
        icon: 'ios-construct',
        authMark: '7',
        isShow: true,
        children: [
            {
                id: '7-1',
                path: '/sub-vue2/decoration/decorateAudit/list',
                title: '装修审核',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-decoration-decorateAudit-list',
                parentName: 'decoration',
                authMark: '7-1',
                isShow: true,
            },
            {
                id: '7-2',
                path: '/sub-vue2/decoration/decorateAudit/detail',
                title: '装修审核详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-decoration-decorateAudit-detail',
                activeName: 'sub-vue2-decoration-decorateAudit-list',
                parentName: 'decoration',
                authMark: '7-1',
                isShow: true,
            },
            {
                id: '7-3',
                path: '/sub-vue2/decoration/directlyStoreSign/list',
                title: '直营门店签署管理',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-decoration-directlyStoreSign-list',
                parentName: 'decoration',
                authMark: '7-2',
                isShow: true,
            },
            {
                id: '7-4',
                path: '/sub-vue2/decoration/directlyStoreSign/check',
                title: '装修审核详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-decoration-directlyStoreSign-check',
                activeName: 'sub-vue2-decoration-directlyStoreSign-list',
                parentName: 'decoration',
                authMark: '7-2',
                isShow: true,
            },
        ],
    },
    {
        id: '8',
        path: '/group',
        name: 'group',
        title: '集团管理',
        icon: 'ios-folder-open',
        authMark: '8',
        isShow: true,
        children: [
            {
                id: '8-1',
                path: '/sub-vue2/group/groupCus/list',
                title: '集团客户',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-group-groupCus-list',
                parentName: 'group',
                authMark: '8-1',
                isShow: true,
            },
            {
                id: '8-2',
                path: '/sub-vue2/group/groupCus/edit',
                title: '集团客户详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-group-groupCus-edit',
                activeName: 'sub-vue2-group-groupCus-list',
                parentName: 'group',
                authMark: '8-1',
                isShow: true,
            },
            {
                id: '8-3',
                path: '/sub-vue2/group/groupBidding/index',
                title: '集团客户招标',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-group-groupBidding-index',
                parentName: 'group',
                authMark: '8-2',
                isShow: true,
            },
            {
                id: '8-4',
                path: '/sub-vue2/group/groupBidding/detail',
                title: '装修审核详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-group-groupBidding-detail',
                activeName: 'sub-vue2-group-groupBidding-index',
                parentName: 'group',
                authMark: '8-2',
                isShow: true,
            },
        ],
    },
    {
        id: '9',
        path: '/statistics',
        name: 'statistics',
        title: '统计中心',
        icon: 'md-pie',
        authMark: '9',
        isShow: true,
        children: [
            {
                id: '9-1',
                path: '/sub-vue2/statistics/stock/list',
                title: '扫码库存',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-stock-list',
                parentName: 'statistics',
                authMark: '9-1',
                isShow: true,
            },
            {
                id: '9-2',
                path: '/sub-vue2/statistics/rebate/list',
                title: '经销商扫码有效统计',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-rebate-list',
                parentName: 'statistics',
                authMark: '9-2',
                isShow: true,
            },
            {
                id: '9-3',
                path: '/sub-vue2/statistics/rebate/detail',
                title: '经销商扫码有效统计详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-rebate-detail',
                activeName: 'sub-vue2-statistics-rebate-list',
                parentName: 'statistics',
                authMark: '9-2',
                isShow: true,
            },
            {
                id: '9-4',
                path: '/sub-vue2/statistics/store/rebate',
                title: '门店积分返利',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-store-rebate',
                parentName: 'statistics',
                authMark: '9-3',
                isShow: true,
            },
            {
                id: '9-5',
                path: '/sub-vue2/statistics/store/rebateDetail',
                title: '返利明细',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-store-rebateDetail',
                activeName: 'sub-vue2-statistics-store-rebate',
                parentName: 'statistics',
                authMark: '9-3',
                isShow: true,
            },
            {
                id: '9-6',
                path: '/sub-vue2/statistics/store/integralDetail',
                title: '积分明细',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-store-integralDetail',
                activeName: 'sub-vue2-statistics-store-rebate',
                parentName: 'statistics',
                authMark: '9-3',
                isShow: true,
            },
            {
                id: '9-7',
                path: '/sub-vue2/statistics/store/task',
                title: '门店任务完成数详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-store-task',
                activeName: 'sub-vue2-statistics-store-rebate',
                parentName: 'statistics',
                authMark: '9-3',
                isShow: true,
            },
            {
                id: '9-8',
                path: '/sub-vue2/statistics/group/list',
                title: '集团单位发票/发货单统计',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-group-list',
                parentName: 'statistics',
                authMark: '9-4',
                isShow: true,
            },
            {
                id: '9-9',
                path: '/sub-vue2/statistics/group/detail',
                title: '集团单位发票/发货单统计详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-group-detail',
                activeName: 'sub-vue2-statistics-group-list',
                parentName: 'statistics',
                authMark: '9-4',
                isShow: true,
            },
            {
                id: '9-10',
                path: '/sub-vue2/statistics/cruise/list',
                title: '业务员巡店统计表',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-cruise-list',
                parentName: 'statistics',
                authMark: '9-5',
                isShow: true,
            },
            {
                id: '9-11',
                path: '/sub-vue2/statistics/cruise/detail',
                title: '业务员巡店统计表明细',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-cruise-detail',
                activeName: 'sub-vue2-statistics-cruise-list',
                parentName: 'statistics',
                authMark: '9-5',
                isShow: true,
            },
            {
                id: '9-12',
                path: '/sub-vue2/statistics/cruise/store',
                title: '巡店记录',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-cruise-store',
                activeName: 'sub-vue2-statistics-cruise-list',
                parentName: 'statistics',
                authMark: '9-5',
                isShow: true,
            },
            {
                id: '9-13',
                path: '/sub-vue2/statistics/storeSign/list',
                title: '签署门店销售任务量',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-storeSign-list',
                parentName: 'statistics',
                authMark: '9-6',
                isShow: true,
            },
            {
                id: '9-14',
                path: '/sub-vue2/statistics/storeSign/check',
                title: '签署门店销售任务量详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-storeSign-check',
                activeName: 'sub-vue2-statistics-storeSign-list',
                parentName: 'statistics',
                authMark: '9-6',
                isShow: true,
            },
            {
                id: '9-15',
                path: '/sub-vue2/statistics/storeSign/checkCurrent',
                title: '签署门店销售任务量详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-storeSign-checkCurrent',
                activeName: 'sub-vue2-statistics-storeSign-list',
                parentName: 'statistics',
                authMark: '9-6',
                isShow: true,
            },
            {
                id: '9-16',
                path: '/sub-vue2/statistics/inspection/list',
                title: '门店店检统计',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-inspection-list',
                parentName: 'statistics',
                authMark: '9-7',
                isShow: true,
            },
            {
                id: '9-17',
                path: '/sub-vue2/statistics/yearInspection/list',
                title: '门店店检年度统计',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-yearInspection-list',
                parentName: 'statistics',
                authMark: '9-8',
                isShow: true,
            },
            {
                id: '9-18',
                path: '/sub-vue2/statistics/rentSubsidy/list',
                title: '新零售补贴审核',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-rentSubsidy-list',
                parentName: 'statistics',
                authMark: '9-9',
                isShow: true,
            },
            {
                id: '9-19',
                path: '/sub-vue2/statistics/credit/handingFeeList',
                title: '授信手续费统计',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-credit-handingFeeList',
                parentName: 'statistics',
                authMark: '9-10',
                isShow: true,
            },
            {
                id: '9-20',
                path: '/sub-vue2/statistics/swordsmanSignRebate/list',
                title: '侠系列签约返利',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-swordsmanSignRebate-list',
                parentName: 'statistics',
                authMark: '9-11',
                isShow: true,
            },
            {
                id: '9-21',
                path: '/sub-vue2/statistics/swordsmanSignRebate/detail',
                title: '查看侠系列返利明细',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-swordsmanSignRebate-detail',
                activeName: 'sub-vue2-statistics-swordsmanSignRebate-list',
                parentName: 'statistics',
                authMark: '9-11',
                isShow: true,
            },
            {
                id: '9-22',
                path: '/sub-vue2/statistics/dealerScanScore/index',
                title: '经销商扫码积分',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-statistics-dealerScanScore-index',
                parentName: 'statistics',
                authMark: '9-12',
                isShow: true,
            },
        ],
    },
    {
        id: '10',
        path: '/sales',
        name: 'sales',
        title: '线上轮胎销售',
        icon: 'md-appstore',
        authMark: '10',
        isShow: true,
        children: [
            {
                id: '10-1',
                path: '/sub-vue2/sales/order/list',
                title: '销售订单',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-sales-order-list',
                parentName: 'sales',
                authMark: '10-1',
                isShow: true,
            },
            {
                id: '10-2',
                path: '/sub-vue2/sales/order/orderDetail',
                title: '销售订单详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-sales-order-orderDetail',
                activeName: 'sub-vue2-sales-order-list',
                parentName: 'sales',
                authMark: '10-1',
                isShow: true,
            },
            {
                id: '10-3',
                path: '/sub-vue2/sales/rebateAudit/list',
                title: '购胎入库返利',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-sales-rebateAudit-list',
                parentName: 'sales',
                authMark: '10-2',
                isShow: true,
            },
            {
                id: '10-4',
                path: '/sub-vue2/sales/rebateAudit/detail',
                title: '购胎入库返利详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-sales-rebateAudit-detail',
                activeName: 'sub-vue2-sales-rebateAudit-list',
                parentName: 'sales',
                authMark: '10-2',
                isShow: true,
            },
            {
                id: '10-5',
                path: '/sub-vue2/sales/storePay/list',
                title: '月度门店线上支付统计',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-sales-storePay-list',
                parentName: 'sales',
                authMark: '10-3',
                isShow: true,
            },
            {
                id: '10-6',
                path: '/sub-vue2/sales/storePay/detail',
                title: '门店线上支付明细',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-sales-storePay-detail',
                activeName: 'sub-vue2-sales-storePay-list',
                parentName: 'sales',
                authMark: '10-3',
                isShow: true,
            },
            {
                id: '10-7',
                path: '/sub-vue2/sales/storePay/refundDetail',
                title: '门店线上退款明细',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-sales-storePay-refundDetail',
                activeName: 'sub-vue2-sales-storePay-list',
                parentName: 'sales',
                authMark: '10-3',
                isShow: true,
            },
            {
                id: '10-8',
                path: '/sub-vue2/sales/storePay/orderDetail',
                title: '销售订单详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-sales-storePay-orderDetail',
                activeName: 'sub-vue2-sales-storePay-list',
                parentName: 'sales',
                authMark: '10-3',
                isShow: true,
            },
        ],
    },
    {
        id: '11',
        path: '/assets',
        name: 'assets',
        title: '资产中心',
        icon: 'logo-yen',
        authMark: '11',
        isShow: true,
        children: [
            {
                id: '11-1',
                path: '/sub-vue2/assets/withdrawal/index',
                title: '提现',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-withdrawal-index',
                parentName: 'assets',
                authMark: '11-1',
                isShow: true,
            },
            {
                id: '11-2',
                path: '/sub-vue2/assets/withdrawal/form',
                title: '余额提现',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-withdrawal-form',
                activeName: 'sub-vue2-assets-withdrawal-index',
                parentName: 'assets',
                authMark: '11-1',
                isShow: true,
            },
            {
                id: '11-3',
                path: '/sub-vue2/assets/withdrawal/result',
                title: '余额提现',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-withdrawal-result',
                activeName: 'sub-vue2-assets-withdrawal-index',
                parentName: 'assets',
                authMark: '11-1',
                isShow: true,
            },
            {
                id: '11-4',
                path: '/sub-vue2/assets/withdrawal/list',
                title: '提现记录',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-withdrawal-list',
                activeName: 'sub-vue2-assets-withdrawal-index',
                parentName: 'assets',
                authMark: '11-1',
                isShow: true,
            },
            {
                id: '11-5',
                path: '/sub-vue2/assets/reconciliation/index',
                title: '对账',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-reconciliation-index',
                parentName: 'assets',
                authMark: '11-2',
                isShow: true,
            },
            {
                id: '11-6',
                path: '/sub-vue2/assets/dealerAccount/list',
                title: '账户管理',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-7',
                path: '/sub-vue2/assets/dealerAccount/detail',
                title: '账户详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-detail',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-8',
                path: '/sub-vue2/assets/dealerAccount/typeChose',
                title: '创建账户',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-typeChose',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-9',
                path: '/sub-vue2/assets/dealerAccount/tiedCardForm',
                title: '账户管理',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-tiedCardForm',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-10',
                path: '/sub-vue2/assets/dealerAccount/tiedCardFormAgain',
                title: '账户管理',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-tiedCardFormAgain',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-11',
                path: '/sub-vue2/assets/dealerAccount/tiedCardApprove',
                title: '绑定卡认证',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-tiedCardApprove',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-12',
                path: '/sub-vue2/assets/dealerAccount/tiedCardResult',
                title: '绑定卡认证结果',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-tiedCardResult',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-13',
                path: '/sub-vue2/assets/dealerAccount/openAccount',
                title: '开户',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-openAccount',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-14',
                path: '/sub-vue2/assets/dealerAccount/openAccountResult',
                title: '开户结果',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-openAccountResult',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-15',
                path: '/sub-vue2/assets/dealerAccount/signContract',
                title: '签约',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-signContract',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-16',
                path: '/sub-vue2/assets/dealerAccount/signContractResult',
                title: '签约结果',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-signContractResult',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-17',
                path: '/sub-vue2/assets/dealerAccount/addBankCard',
                title: '添加银行卡',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-addBankCard',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
            {
                id: '11-18',
                path: '/sub-vue2/assets/dealerAccount/addBankCardResult',
                title: '添加银行卡结果',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-assets-dealerAccount-addBankCardResult',
                activeName: 'sub-vue2-assets-dealerAccount-list',
                parentName: 'assets',
                authMark: '11-3',
                isShow: true,
            },
        ],
    },
    {
        id: '12',
        path: '/setting',
        name: 'setting',
        title: '系统设置',
        icon: 'md-settings',
        authMark: '12',
        isShow: true,
        children: [
            {
                id: '12-1',
                path: '/sub-vue2/setting/account/list',
                title: '账号管理',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-setting-account-list',
                parentName: 'setting',
                authMark: '12-1',
                isShow: true,
            },
            {
                id: '12-2',
                path: '/sub-vue2/setting/account/edit',
                title: '账号详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-setting-account-edit',
                activeName: 'sub-vue2-setting-account-list',
                parentName: 'setting',
                authMark: '12-1',
                isShow: true,
            },
            {
                id: '12-3',
                path: '/sub-vue2/setting/role/list',
                title: '角色管理',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-setting-role-list',
                parentName: 'setting',
                authMark: '12-2',
                isShow: true,
            },
            {
                id: '12-4',
                path: '/sub-vue2/setting/role/edit',
                title: '角色管理详情',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-setting-role-edit',
                activeName: 'sub-vue2-setting-role-list',
                parentName: 'setting',
                authMark: '12-2',
                isShow: true,
            },
            {
                id: '12-5',
                path: '/sub-vue2/setting/company/add',
                title: '企业认证',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-setting-company-add',
                parentName: 'setting',
                authMark: '12-3',
                isShow: true,
            },
            {
                id: '12-6',
                path: '/sub-vue2/setting/company/result',
                title: '企业认证结果',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-setting-company-result',
                activeName: 'sub-vue2-setting-company-add',
                parentName: 'setting',
                authMark: '12-3',
                isShow: true,
            },
        ],
    },

    {
        id: '13',
        path: '/test',
        name: 'test',
        title: 'vue3测试',
        icon: 'md-settings',
        authMark: '13',
        isShow: true,
        children: [
            {
                id: '13-1',
                path: '/sub-vue3/test/home/list',
                title: 'vue3首页',
                applyName: 'sub-vue3',
                auth: true,
                name: 'sub-vue3-test-home-list',
                parentName: 'test',
                authMark: '13-1',
                isShow: true,
            },
            {
                id: '13-2',
                path: '/sub-vue3/test/home/detail',
                title: 'vue3首页详情',
                applyName: 'sub-vue3',
                auth: true,
                name: 'sub-vue3-test-home-detail',
                activeName: 'sub-vue3-test-home-list',
                parentName: 'test',
                authMark: '13-1',
                isShow: true,
            },
            {
                id: '13-3',
                path: '/sub-vue3/test/pageA/list',
                title: 'vue3-pageA页面',
                applyName: 'sub-vue3',
                auth: true,
                name: 'sub-vue3-test-pageA-list',
                parentName: 'test',
                authMark: '13-2',
                isShow: true,
            },
            {
                id: '13-4',
                path: '/sub-vue3/test/previewPdf/index',
                title: 'vue3-预览PDF',
                applyName: 'sub-vue3',
                auth: true,
                name: 'sub-vue3-test-previewPdf-index',
                parentName: 'test',
                authMark: '13-3',
                isShow: true,
            },
        ],
    },
];
// 左侧菜单权限（当接口挂了的时候，可以暂时用这个）
const authMarkList = [
    '1',
    '2',
    '3',
    '3-1',
    '3-2',
    '4',
    '4-1',
    '4-2',
    '4-3',
    '4-4',
    '5',
    '5-1',
    '5-2',
    '5-3',
    '5-4',
    '5-5',
    '6',
    '6-1',
    '6-2',
    '6-3',
    '6-4',
    '6-5',
    '7',
    '7-1',
    '7-2',
    '8',
    '8-1',
    '8-2',
    '9',
    '9-1',
    '9-2',
    '9-3',
    '9-4',
    '9-5',
    '9-6',
    '9-7',
    '9-8',
    '9-9',
    '9-10',
    '9-11',
    '9-12',
    '10',
    '10-1',
    '10-2',
    '10-3',
    '11',
    '11-1',
    '11-2',
    '11-3',
    '12',
    '12-1',
    '12-2',
    '12-3',
    '13',
    '13-1',
    '13-2',
    '13-3',
];
// 模拟接口数据
const resData = {
    id: '342',
    createDate: '2020-10-08 08:43:54',
    modifyDate: '2024-02-06 14:49:14',
    realName: '老李',
    userName: '18857375652',
    mobile: '18857375652',
    email: null,
    enabledDate: null,
    isMaster: true,
    password: '57091af1260966a65cf521d4fe1eb63b',
    distributorId: '218',
    loginFailureCount: 0,
    certificationStatus: 1,
    certificationName: '北京医科智谷资讯有限公司',
    isLocked: false,
    remark: null,
    lockedDate: '2022-11-29 17:21:30',
    isPda: true,
    isLoginRemind: false,
    isEnabled: true,
    isDelete: false,
    distributorName: 'test-不要动服务部',
    isPdaChooseStore: true,
    roleDTOS: null,
    roleTye: false,
    menu: [], // 菜单
};

export { siderTreeList, authMarkList, resData };
