// 左侧菜单tree
const siderTreeList = [
    {
        id: '1',
        path: '/home',
        title: '首页',
        icon: 'md-home',
        applyName: 'base',
        auth: true,
        name: 'home',
        authMark: '1',
        isShow: true,
    },
    // sub-vue2
    {
        id: '2',
        path: '/sub-vue2/export/exportList',
        title: '导出列表2',
        applyName: 'sub-vue2',
        icon: 'md-download',
        auth: true,
        name: 'sub-vue2-export-exportList',
        authMark: '2',
        isShow: true,
    },
    {
        id: '3',
        path: '/customer',
        name: 'customer',
        title: '客户管理2',
        icon: 'ios-archive',
        authMark: '3',
        isShow: true,
        children: [
            {
                id: '3-1',
                path: '/sub-vue2/customer/customerManage',
                title: '客户管理',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-customer-customerManage',
                parentName: 'customer',
                authMark: '3-1',
                isShow: true,
            },
            {
                id: '3-2',
                path: '/sub-vue2/customer/customerManage/detail',
                title: '客户管理详情',
                icon: '',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-customer-customerManage-detail',
                activeName: 'sub-vue2-customer-customerManage',
                parentName: 'customer',
                authMark: '3-1',
                isShow: true,
            },
            {
                id: '3-3',
                path: '/sub-vue2/customer/userApply',
                title: '客户申请',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-customer-userApply',
                parentName: 'customer',
                authMark: '3-2',
                isShow: true,
            },
            {
                id: '3-4',
                path: '/sub-vue2/customer/userApply/detail',
                title: '客户申请详情',
                icon: '',
                applyName: 'sub-vue2',
                auth: true,
                name: 'sub-vue2-customer-userApply-detail',
                activeName: 'sub-vue2-customer-userApply',
                parentName: 'customer',
                authMark: '3-2',
                isShow: true,
            },
        ],
    },
    // sub-vue3
    {
        id: '4',
        path: '/sub-vue3/export/exportList',
        title: '导出列表3',
        applyName: 'sub-vue3',
        icon: 'md-download',
        auth: true,
        name: 'sub-vue3-export-exportList',
        authMark: '4',
        isShow: true,
    },
    {
        id: '5',
        path: '/user',
        name: 'user',
        title: '用户管理3',
        icon: 'ios-archive',
        authMark: '5',
        isShow: true,
        children: [
            {
                id: '5-1',
                path: '/sub-vue3/user/userManage',
                title: '用户管理',
                applyName: 'sub-vue3',
                auth: true,
                name: 'sub-vue3-user-userManage',
                parentName: 'user',
                authMark: '5-1',
                isShow: true,
            },
            {
                id: '5-2',
                path: '/sub-vue3/user/userManage/userDetail',
                title: '用户管理详情',
                icon: '',
                applyName: 'sub-vue3',
                auth: true,
                name: 'sub-vue3-user-userManage-userDetail',
                activeName: 'sub-vue3-user-userManage',
                parentName: 'user',
                authMark: '5-1',
                isShow: true,
            },
            {
                id: '5-3',
                path: '/sub-vue3/user/userApply',
                title: '用户申请',
                applyName: 'sub-vue3',
                auth: true,
                name: 'sub-vue3-user-userApply',
                parentName: 'user',
                authMark: '5-2',
                isShow: true,
            },
            {
                id: '5-4',
                path: '/sub-vue3/user/userApply/applyDetail',
                title: '用户申请详情',
                icon: '',
                applyName: 'sub-vue3',
                auth: true,
                name: 'sub-vue3-user-userApply-applyDetail',
                activeName: 'sub-vue3-user-userApply',
                parentName: 'user',
                authMark: '5-2',
                isShow: true,
            },
        ],
    },
    {
        id: '6',
        path: '/functionDemo',
        name: 'functionDemo',
        title: '功能示例',
        icon: 'ios-archive',
        authMark: '6',
        isShow: true,
        children: [
            {
                id: '6-1',
                path: '/sub-vue3/functionDemo/imgDotting',
                title: '图片上打点',
                applyName: 'sub-vue3',
                auth: true,
                name: 'sub-vue3-functionDemo-imgDotting',
                parentName: 'functionDemo',
                authMark: '6-1',
                isShow: true,
            }
        ]
    }
];
// 左侧菜单权限（当接口挂了的时候，可以暂时用这个）
const authMarkList = ['1', '2', '3', '3-1', '3-2', '3-3', '3-4', '4', '5', '5-1', '5-2', '5-3', '5-4', '6', '6-1'];
// 模拟接口数据
const resData = {
    id: '342',
    createDate: '2020-10-08 08:43:54',
    modifyDate: '2024-02-06 14:49:14',
    realName: '老李',
    userName: '18857375652',
    mobile: '18857375652',
    email: null,
    enabledDate: null,
    isMaster: true,
    password: '57091af1260966a65cf521d4fe1eb63b',
    distributorId: '218',
    loginFailureCount: 0,
    certificationStatus: 1,
    certificationName: '北京医科智谷资讯有限公司',
    isLocked: false,
    remark: null,
    lockedDate: '2022-11-29 17:21:30',
    isPda: true,
    isLoginRemind: false,
    isEnabled: true,
    isDelete: false,
    distributorName: 'test-不要动服务部',
    isPdaChooseStore: true,
    roleDTOS: null,
    roleTye: false,
    menu: [], // 菜单
};

export { siderTreeList, authMarkList, resData };
